app1/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include,url

urlpatterns = [

    url(r'^$', views.index,name='index'),
    url(r'^main/', views.main,name='main'),
    url(r'^main1/', views.main1,name='main1'),
    url(r'^main2/', views.main2,name='main2'),

    url(r'^H_req_for_managers/', views.H_req_for_managers, name='H_req_for_managers'),
    url(r'^Today_req_for_managers/', views.Today_req_for_managers, name='Today_req_for_managers'),

    url(r'^Request_to_Leave_V/', views.Request_to_Leave_V,name='Request_to_Leave_V'),
    url(r'^H_req_for_employees/', views.H_req_for_employees,name='H_req_for_employees'),
    url(r'^Today_req_for_employees/', views.Today_req_for_employees,name='Today_req_for_employees'),
   
    url(r'^(?P<id>[0-9a-f-]+)/Approved/$', views.Approve, name='Approve'),
    url(r'^(?P<id>[0-9a-f-]+)/Reject/$', views.Reject, name='Reject'),

    url(r'^Admision/', views.Request_to_Leave_V, name='Request_to_Leave_V'),

    url(r'^success/', views.success, name='success'),
    url(r'^addition_Forbidden/', views.addition_Forbidden, name='addition_Forbidden'),




    
# ===========================================================================================

# ==================================================================================================
# ==========================================================================================
#     
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#(?P<pk>\d+)

test1/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app1/', include('app1.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^chaining/', include('smart_selects.urls')),

    # url(r'^ajax_search/',include('ajax_search.urls')),


] 
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
# Create your models here.
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid
import os
from datetime import datetime, timedelta
from datetime import date
from django.utils.timezone import now
import datetime
from multiselectfield import MultiSelectField
from decimal import Decimal
from smart_selects.db_fields import ChainedForeignKey,ChainedManyToManyField,GroupedForeignKey
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw  

def get_file_path1(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)

def get_file_path01(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)
    return os.path.join('working_emp', filename)   
def get_file_path02(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)
    return os.path.join('retired_emp', filename)     
def get_file_path2(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)
    return os.path.join('cartridges', filename)
def get_file_path3(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)
    return os.path.join('spareparts', filename)
def get_file_path4(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s.%s" % ( datetime.datetime.now(),uuid.uuid4(), ext)
    return os.path.join('passrecovery', filename)
class Leave_Requests(models.Model):
      reasons=(('Work',' Work'),('Emergency','Emergency'))
      leave_type=(('With return',' With return'),('No Return','No Return'))
      employee_name = models.CharField(null=True,max_length=120, verbose_name='Employee Name ')
      department_name = models.CharField(max_length=120, verbose_name='Department Number ')
      time_to_leave = models.DateField(auto_now_add=True, auto_now=False,null=True)
      uuid = models.CharField(max_length=120,default=uuid.uuid4)
      qr_code    = models.ImageField(upload_to='qr_codes', blank=True)
      request_status = models.BooleanField(default=False)
      request_revised = models.BooleanField(default=False)  
      leave_reason = models.CharField(max_length=120,choices=reasons, verbose_name='Leaving For ... ')  
      leave_type = models.CharField(max_length=120,blank=True,choices=leave_type, verbose_name='Leave Type ')  

      def get_absolute_url(self):
          return "/app1/%s/" % (self.id)

      def __str__(self):
          return str(self.uuid)

      def save(self, *args, **kwargs):
          qrcode_img = qrcode.make(self.uuid)
          canvas = Image.new('RGB', (290, 290), 'white')
          canvas.paste(qrcode_img)
          fname = f'qr_code-{self.uuid}.png'
          buffer = BytesIO()
          canvas.save(buffer,'PNG')
          self.qr_code.save(fname, File(buffer), save=False)
          canvas.close()
          super().save(*args, **kwargs)

app1/views.py
from django.db.models import *
from django.db.models import  Expression
from django.http import HttpResponse,HttpRequest,HttpResponseRedirect,request
from django.shortcuts import render
from .form import  Aprove_Reject_form,Leave_request_form
from django.urls import reverse
from app1.models import Leave_Requests
from datetime import datetime, timedelta
from datetime import date
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
import json
import uuid
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from itertools import chain
from django import template
from django.contrib.auth.models import Group
from django.utils.timezone import now
from datetime import timedelta as tdelta
from django.utils import timezone
from django.core import serializers
import time
from decimal import Decimal
from django.db.models.functions import ExtractMonth




###########################################################################################




#############################################################################################

def index(request):
    return HttpResponse("<center><h1>here you are Osama</h1></center>")




# =======================================
# =======================================
# =======================================
# =======================================
# ==========================================
# ****************************************=======================================
# =======================================
# =======================================
# =======================================
# ==========================================
# ****************************************=======================================
# =======================================
# =======================================
# =======================================
# ==========================================
# ****************************************=======================================
# =======================================
# =======================================
@login_required
def addition_Forbidden(request):
    return render(request, "addition_Forbidden.html", {})
# =======================================

@login_required
def success(request):
    return render(request,"success.html", {}) 
# ==========================================
@login_required
def main(request):
    if request.user.groups.filter(name='employees') :
       return HttpResponseRedirect(reverse('main1'))
    elif request.user.groups.filter(name='managers'):
       return HttpResponseRedirect(reverse('main2'))
# ****************************************

register = template.Library()
#loggedadmin = request.user
@register.filter(name='has_group')

def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False
    #----------------------------------------------------------
@login_required
def Request_to_Leave_V(request):

    form = Leave_request_form((request.POST or None))
    title2 = ""
    if form.is_valid():
        request.session['form-submitted'] = True
        instance = form.save(commit=False)
        instance.employee_name = request.user.get_full_name()
        if has_group(request.user,"Finance"):
           instance.department_name="Finance"
        elif  has_group(request.user,"IT"): 
              instance.department_name="IT"
        elif  has_group(request.user,"Investment"): 
              instance.department_name="Investment"                    
        instance.time_to_leave=datetime.now()
        instance.save()
        return HttpResponseRedirect(reverse('success'))


    context = { "form": form,}
    return render(request, "Admision.html", context)

#--------------------------------------------------
@login_required
def main1(request):
    return render(request, "index.html", {})
#----------------------------------------------------
@login_required
def main2(request):
    return render(request, "index2.html", {})    
#-----------------------------------------------------------
@login_required
def H_req_for_managers(request,id=None):
    today = str(date.today())
    if has_group(request.user,"IT"):
       requests = Leave_Requests.objects.all().filter(department_name='IT').order_by('time_to_leave')
    elif has_group(request.user,"Investment"):
       requests = cartridges.objects.all().filter(department_name='Investment').order_by('time_to_leave')
    elif has_group(request.user,"Finance"):
       requests = cartridges.objects.all().filter(department_name='Finance').order_by('time_to_leave')
  
    return render(request, "H_req_for_managers.html", { "requests":requests,})

#----------------------------------------------------------------------
@login_required
def H_req_for_employees(request,id=None):
    today = str(date.today())
    requests = Leave_Requests.objects.all().filter(employee_name=request.user.get_full_name()).order_by('time_to_leave')
    return render(request, "H_req_for_employees.html", { "requests":requests,})    
#----------------------------------------------------------------------
@login_required
def Today_req_for_managers(request,id=None):
    today = str(date.today())
    if has_group(request.user,"IT"):
       requests = Leave_Requests.objects.all().filter(department_name='IT').order_by('time_to_leave')
    elif has_group(request.user,"Investment"):
       requests = cartridges.objects.all().filter(department_name='Investment').order_by('time_to_leave')
    elif has_group(request.user,"Finance"):
       requests = cartridges.objects.all().filter(department_name='Finance').order_by('time_to_leave')
  
    return render(request, "Today_req_for_managers.html", { "requests":requests,})

#----------------------------------------------------------------------
@login_required
def Today_req_for_employees(request,id=None):
    today = str(date.today())
    requests = Leave_Requests.objects.all().filter(employee_name=request.user.get_full_name()).filter(time_to_leave=today).order_by('id')
    return render(request, "Today_req_for_employees.html", { "requests":requests,})    
#--------------------------------------
@login_required
def Today_req_for_managers(request,id=None):
    today = str(date.today())
    if has_group(request.user,"IT"):
       requests = Leave_Requests.objects.all().filter(department_name='IT').filter(time_to_leave=today).order_by('time_to_leave')
    elif has_group(request.user,"Investment"):
       requests = Leave_Requests.objects.all().filter(department_name='Investment').filter(time_to_leave=today).order_by('time_to_leave')
    elif has_group(request.user,"Finance"):    
       requests = Leave_Requests.objects.all().filter(department_name='Finance').filter(time_to_leave=today).order_by('time_to_leave')

    
    return render(request, "Today_req_for_managers.html", { "requests":requests,})        
#======================================================================================
# 
# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
@login_required
def Approve(request,id=None):
    Request = get_object_or_404(Leave_Requests,id=id)  
    if Request.request_revised == True:
       return HttpResponseRedirect(reverse('addition_Forbidden')) 
    else:
       Request.request_status = True
       Request.request_revised = True       
       Request.save()
       return HttpResponseRedirect(reverse('success')) 












#----------------------------------------------------------------------------
@login_required
def  Reject(request,id=None):
    Request = get_object_or_404(Leave_Requests,id=id)  
    if Request.request_revised == True:
       return HttpResponseRedirect(reverse('addition_Forbidden')) 
    else:
       Request.request_status = False
       Request.request_revised = True       
       Request.save()
       return HttpResponseRedirect(reverse('success'))  
     

app1/templates/Admision.html
 {% extends 'base.html' %}
 {% include 'navbar.html' %}
{%  load static %}
{% load staticfiles %}
{% load crispy_forms_tags %}


{% block content %}
<!--<script src='{% static "js/jquery-3.1.1.min.js"  %}'></script>-->
<!--<script src='{% static "js/bootstrap.min.js"  %}'></script>-->
<script src='{% static "js/moment.min.js"  %}'></script>
<script src='{% static "js/bootstrap-datetimepicker.js"  %}'></script>
<link href='{% static   "css/bootstrap-datetimepicker.min.css"  %}' rel="stylesheet">

<script type="text/javascript">
$(function () {
    $('.datepicker').datetimepicker(
    {
        format: 'YYYY-MM-DD HH:mm:ss',
        sideBySide: true
    }
    );
});
</script>


<style>
.conatiner{
margin-top: 70px;
margin-bottom: 70px;
}
.vv{
background-color: #004C99
}

#id_leave_reason{
    font-size:15;
    height:55px;
    font-style:bold;
}
#id_leave_type{
        font-size:15;
    height:55px;
    font-style:bold;
}
form-control  .select {

    height:100px;
}
</style>


<div class="conatiner" >

<div class="row align-items-center justify-content-center" style=""><div class="col-md-8 justify-content-center text-white list-group-item vv" ><h1 style="color:#ffffff">Request To Leave</h1></div></div>

<div class="row align-items-center justify-content-center"">
 <div class="col-md-8 bg-faded">

 <form method='POST' action= ''>{% csrf_token %}

<b style='    font-family:Arial, Helvetica, sans-serif;height:55px'>
 {{form|crispy}}
 </b>
 <center>
  <input class= 'btn btn-primary btn-lg'  value="REQUEST LEAVE" type=submit onClick="{{  clicker }}">

 <p></p>
  <input class= 'btn btn-primary btn-lg' value="CANCEL" type=reset >

 </center>
 </form>
 </div>
</div>
</div>
<!--
 <div class="col-md-4">

 <form method='POST' action= ''>{% csrf_token %}

 {{form|crispy}}
<a class="btn btn-primary" href= {{  clicker }} >clcik me</a>
 <input class= 'btn btn-primary' type=submit  onClick="{{  clicker }}">
 </form>
 </div>

     <div class="col-md-4">

 <form method='POST' action= ''>{% csrf_token %}

 {{form|crispy}}
<a class="btn btn-primary" href= {{  clicker }} >clcik me</a>
 <input class= 'btn btn-primary' type=submit onClick="{{  clicker }}">
 </form>
 </div>
-->




{% endblock %}

app1/templates/H_req_for_employees.html
{% include 'navbar.html' %}

{% load static %}

{% block content %}

<style>
.container
{
  margin-top:20px;
}
    .bb{
 margin-top:90px;

}
.cc{
 margin-top:0px;
 margin-bottom: 90px;
}
 td {
font-family:'Arial, Helvetica, sans-serif';
text-align:center;
font-size:14pt;
}
th{
  text-align:center;
}

</style>
<html>
<body>

<ul class="nav nav-tabs nav nav-tabs nav-pills bb " id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active lead" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><p>PAST REQUESTS</p></a>
  </li>





</ul>

<div class="container">
<table class="table table-hover">
  <thead class="justify-content-center" style="font-family:'Arial, Helvetica, sans-serif';color:white;background-color:blue;text-align:center;">
    <tr>
      <th>ID</th>
      <th>Employee Name</th>
      <th>Department Name</th>
      <th>Date</th>
      <th>Leaving For</th>
      <th>Leaving Type</th>


      <th>Request Status</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in requests %}

   <tr> 
   <th scope="row"> {{ obj.id }}     </th>
   <td>  {{ obj.employee_name }}     </td>
   <td>  {{ obj.department_name }}   </td>
   <td>  {{ obj.time_to_leave }}     </td>
   <td>  {{ obj.leave_reason }}      </td>
   <td>  {{ obj.leave_type }}        </td>
  {% if obj.request_status  %}
   <td> <img class="" src='{% static "imge/ok.png"  %}'  width="30" height="30"></td>
 {% else %}
      <td><img class="" src='{% static "imge/wrong.png"  %}'  width="30" height="30"></td>
  {% endif %}
 
   </tr>

  {% endfor %}
  </tbody>
</table>

</div>














</div></div>







-->








</div></div></div>












</div>






















   {% endblock %}
</body>
</html>

app1/templates/H_req_for_managers.html
{% include 'navbar.html' %}

{% load static %}

{% block content %}

<style>
.container
{
  margin-top:20px;
}
    .bb{
 margin-top:90px;

}
.cc{
 margin-top:0px;
 margin-bottom: 90px;
}
 td {
font-family:'Arial, Helvetica, sans-serif';
text-align:center;
font-size:14pt;
}
th{
  text-align:center;
}

</style>
<html>
<body>

<ul class="nav nav-tabs nav nav-tabs nav-pills bb " id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active lead" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><p>PAST REQUESTS</p></a>
  </li>





</ul>

<div class="container">
<table class="table table-hover">
  <thead class="justify-content-center" style="font-family:'Arial, Helvetica, sans-serif';color:white;background-color:blue;text-align:center;">
    <tr>
      <th>ID</th>
      <th>Employee Name</th>
      <th>Department Name</th>
      <th>Date</th>
      <th>Leaving For</th>
      <th>Leaving Type</th>


      <th>Request Status</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in requests %}

   <tr> 
   <th scope="row"> {{ obj.id }}     </th>
   <td>  {{ obj.employee_name }}     </td>
   <td>  {{ obj.department_name }}   </td>
   <td>  {{ obj.time_to_leave }}     </td>
   <td>  {{ obj.leave_reason }}      </td>
   <td>  {{ obj.leave_type }}        </td>
  {% if obj.request_status  %}
   <td> <img class="" src='{% static "imge/ok.png"  %}'  width="30" height="30"></td>
 {% else %}
      <td><img class="" src='{% static "imge/wrong.png"  %}'  width="30" height="30"></td>
  {% endif %}
 
   </tr>

  {% endfor %}
  </tbody>
</table>

</div>














</div></div>







-->








</div></div></div>












</div>






















   {% endblock %}
</body>
</html>

app1/templates/Today_req_for_employees.html
{% include 'navbar.html' %}

{% load static %}

{% block content %}

<style>
.container
{
  margin-top:20px;
}
    .bb{
 margin-top:90px;

}
.cc{
 margin-top:0px;
 margin-bottom: 90px;
}
 td {
font-family:'Arial, Helvetica, sans-serif';
text-align:center;
font-size:14pt;
}
th{
  text-align:center;
}

</style>
<html>
<body>

<ul class="nav nav-tabs nav nav-tabs nav-pills bb " id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active lead" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><p>REQUESTS</p></a>
  </li>





</ul>

<div class="container">
<table class="table table-hover">
  <thead class="justify-content-center" style="font-family:'Arial, Helvetica, sans-serif';color:white;background-color:blue;text-align:center;">
    <tr>
      <th>ID</th>
      <th>Employee Name</th>
      <th>Department Name</th>
      <th>Date</th>
      <th>Leaving For</th>
      <th>Leaving Type</th>
            <th style="width:70px">QR</th>

      <th>Request Status</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in requests %}

   <tr> 
   <th scope="row"> {{ obj.id }}     </th>
   <td>  {{ obj.employee_name }}     </td>
   <td>  {{ obj.department_name }}   </td>
   <td>  {{ obj.time_to_leave }}     </td>
   <td>  {{ obj.leave_reason }}      </td>
   <td>  {{ obj.leave_type }}        </td>
   <td>{% if   obj.request_revised == False or  obj.request_status == False   %} -----{% else %}<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bd-example-modal-lg">QR-CODE</button>            {% endif %}              </td>
 
  {% if   obj.request_revised == False  %}
   <td> <img class="" src='{% static "imge/waitting.png"  %}'  width="30" height="30"></td>
 {% elif  obj.request_status %}
      <td><img class="" src='{% static "imge/ok.png"  %}'  width="30" height="30"></td>
      <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">



   <center>    {% if obj.request_status %} 
   <img src={{ obj.qr_code.url }} width="400px" height="400px" class="bbb "/>
   {% else %}<img src="{% static 'imge/nofile.jpg' %}" width="100px" height="100px" class=" "/> THERE IS NO FILE ASSOCIATED WITH THIS REQUEST
   {% endif %} </center>



       <button type="button" class="btn btn-secondary btn-lg" data-dismiss="modal">اغلاق</button>
  </div>
  </div></div>
  {% else %}
            <td><img class="" src='{% static "imge/wrong.png"  %}'  width="30" height="30"></td>

  {% endif %}
   </tr>

  {% endfor %}
  </tbody>
</table>

</div>














</div></div>







-->








</div></div></div>












</div>























   {% endblock %}
</body>
</html>

app1/templates/Today_req_for_managers.html
{% include 'navbar.html' %}

{% load static %}

{% block content %}

<style>
.container
{
  margin-top:20px;
}
    .bb{
 margin-top:90px;

}
.cc{
 margin-top:0px;
 margin-bottom: 90px;
}
 td {
font-family:'Arial, Helvetica, sans-serif';
text-align:center;
font-size:14pt;
}
th{
  text-align:center;
}

</style>
<html>
<body>

<ul class="nav nav-tabs nav nav-tabs nav-pills bb " id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active lead" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><p>REQUESTS</p></a>
  </li>





</ul>

<div class="container">
<table class="table table-hover">
  <thead class="justify-content-center" style="font-family:'Arial, Helvetica, sans-serif';color:white;background-color:blue;text-align:center;">
    <tr>
      <th>ID</th>
      <th>Employee Name</th>
      <th>Department Name</th>
      <th>Date</th>
      <th>Leaving For</th>
      <th>Leaving Type</th>
      <th>Request Status</th>
      <th style="width:70px">Actions</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in requests %}

   <tr> 
   <th scope="row"> {{ obj.id }}     </th>
   <td>  {{ obj.employee_name }}     </td>
   <td>  {{ obj.department_name }}   </td>
   <td>  {{ obj.time_to_leave }}     </td>
   <td>  {{ obj.leave_reason }}      </td>
   <td>  {{ obj.leave_type }}        </td>

  {% if   obj.request_revised == False  %}
   <td> <img class="" src='{% static "imge/waitting.png"  %}'  width="30" height="30"></td>
 {% elif  obj.request_status %}
      <td><img class="" src='{% static "imge/ok.png"  %}'  width="30" height="30"></td>
  {% else %}
            <td><img class="" src='{% static "imge/wrong.png"  %}'  width="30" height="30"></td>

  {% endif %}
  <td><a class="btn btn-outline-primary btn-lg " href="{% url 'Approve' id=obj.id %}"  >Accept</a>||<a class="btn btn-outline-primary btn-lg " href="{% url 'Reject' id=obj.id%}"  >Reject</a></td>
   </tr>

  {% endfor %}
  </tbody>
</table>

</div>














</div></div>







-->








</div></div></div>












</div>






















   {% endblock %}
</body>
</html>

app1/templates/base.html
{% load staticfiles %}
{% load static %}
{% include 'navbar.html' %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet">
        <link href="{% static 'css/base.css'  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="{% static 'css/jumbotron.css' %} "rel="stylesheet"> -->
  </head>


  <body>


    <div class="container">
        {% block content %}
<!-- {% include 'jumbo.html' %} -->
              <div class="jumbotron">
        <h1>Navbar example</h1>
        <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
        <a class="btn btn-lg btn-primary" href="../../components/navbar/" role="button">View navbar docs &raquo;</a>
      </div>

    </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js'%}integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script> -->
 {% endblock %}
  </body>
</html>

app1/templates/restricted.html
{% include 'navbar.html' %}

{%  load static %}
{% block content %}


<style>

    .alert{
 margin-top: 200px;

    }
    .rounded{
 margin-top: 80px;

    }

</style>
<html>
<body>
<center>
    <img class="rounded" src='{% static "imge/rest.png"  %}' alt="Generic placeholder image"  width="140" height="140">
          </center>
<div class="alert alert-danger" role="alert">

<CENTER><H1><P>YOU ARE NOT AUTHORIZED TO ACCESS THIS PAGE ...... THIS IS RESTRICTED FORRBIDEN AREA</P></H1></CENTER>

</div>
   {% endblock %}
</body>
</html>